### PR TITLE
New File

### PR DESCRIPTION
**Pull request by Znunu**
This is a slightly different approach

- Should keep the code DRY since the 'remove all buttons' and 'remove some buttons' are just gonna be function calls of the same function
- Will watch when a channel changes and only then remove the buttons. This fixes the problem with delay.
- Will _remove_ a _single_ element per aria label instead of _hiding_ _every_ element per aria label. Maybe I'm missing something and the latter is necessary? In any case the former is more compact which is good, since people can quicker evaluate if the code is legit.

### CODE REVIEW

**Comment by Multarix** [comment]
Honestly the removing multiple elements per label was just me being lazy and copying the code over from my other repo which removes blocked messages.

Ill take a closer look at this and merge it when I get home

**Comment by Multarix** [comment]
Oh also, reasoning for my approach to remove the buttons the way I did, was to keep the code more simple and easier to read. This makes it easier for people with little to no knowledge of js to look at the code and potentially understand it easier.

**Comment by Multarix** [comment]
Oookay, just got around to looking at this, while what you have is "fine" it doesn't quite work, but I understand what you were going for. Here is my version of it, the only problem is it doesn't start working until you have changed channels at least once. (We can either explain this in the documentation, or we can write an extra line or 2 that will remove it by default.

I also want to point out that in the event discord change the aria labels, this will start erroring, so we should also probably add a check to see if the querySelector returns a null.
```js
new MutationObserver(() => {
	const buttonsToHide = ["Open GIF picker", "Open sticker picker", "Send a gift"]
	for(button of buttonsToHide){
		document.querySelector(`[aria-label="${button}"]`).style.display = "none";
	}
}).observe(document.querySelector('title'), {childList: true});
```

**Comment by Znunu** [comment]
Okay, looks good

> Here is my version of it, the only problem is it doesn't start working until you have changed channels at least once. (We can either explain this in the documentation, or we can write an extra line or 2 that will remove it by default.

I'd prefer keeping it clean and adding some info to the docs

> I also want to point out that in the event discord change the aria labels, this will start erroring, so we should also probably add a check to see if the querySelector returns a null.

I think this is fine. If aria labels change, most likely the script should be modified and not just carry on

**Comment by Multarix** [comment]
I also found another issue with this that I have set up an issue for (#3).
Seeing as we're checking for the channel name to change it causes issue when swapping to a channel of the same name.

**Pull request closed without merging**
